// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieLibrary.Data.Models
{
    public partial class Movie
    {
        public int MovieId { get; set; }
        public string Caption { get; set; }
        public int ReleaseYear { get; set; }
        public DateTime InsertDate { get; set; }
        public DateTime? DeleteDate { get; set; }
    }
}