// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace MovieLibrary.Data.Models
{
    public partial class MovielibraryContext : DbContext
    {
        public MovielibraryContext()
        {
        }

        public MovielibraryContext(DbContextOptions<MovielibraryContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MaritalStatus> MaritalStatuses { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=(LocalDb)\\MSSQLLocalDB;Initial Catalog=MovieLibraryCodeFirst;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<MaritalStatus>(entity =>
            {
                entity.Property(e => e.MaritalStatusId)
                    .ValueGeneratedNever()
                    .HasColumnName("MaritalStatusID");

                entity.Property(e => e.Caption)
                    .IsRequired()
                    .HasMaxLength(50);
            });
                        
            modelBuilder.Entity<Movie>(entity =>
            {
                entity.Property(e => e.MovieId).HasColumnName("MovieID");

                entity.Property(e => e.Caption)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.DeleteDate).HasColumnType("datetime");

                entity.Property(e => e.InsertDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.Property(e => e.UserId).HasColumnName("UserID");

                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(512);

                entity.Property(e => e.DeleteDate).HasColumnType("datetime");

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Idnumber)
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnName("IDNumber");

                entity.Property(e => e.InsertDate).HasColumnType("datetime");

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MaritalStatusId).HasColumnName("MaritalStatusID");

                entity.HasOne(d => d.MaritalStatus)
                    .WithMany(p => p.Users)
                    .HasForeignKey(d => d.MaritalStatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Users_MaritalStatuses");
            });

            modelBuilder.Entity<User>().HasData(
                new User { UserId = 1, FirstName = "John", LastName = "Doe", Address = "123 Main St", Idnumber = "123456789", MaritalStatusId = 1, InsertDate = DateTime.ParseExact("2021-12-22 18:30:28.537", "yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture), DeleteDate = null },
                new User { UserId = 2, FirstName = "Jane", LastName = "Doe", Address = "321 5th St", Idnumber = "987654321", MaritalStatusId = 3, InsertDate = DateTime.ParseExact("2021-12-22 18:40:11.610", "yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture), DeleteDate = null });

            modelBuilder.Entity<MaritalStatus>().HasData(
                new MaritalStatus { MaritalStatusId = 1, Caption = "Single" },
                new MaritalStatus { MaritalStatusId = 2, Caption = "Married" },
                new MaritalStatus { MaritalStatusId = 3, Caption = "Divorced" },
                new MaritalStatus { MaritalStatusId = 4, Caption = "Widowed" });

            modelBuilder.Entity<Movie>().HasData(
                new Movie { MovieId = 1, Caption = "The Wolf of Wallstreet", ReleaseYear = 2013, MovieLength = 180, InsertDate = DateTime.ParseExact("2021-12-21 15:50:35.703", "yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture), DeleteDate = null },
                new Movie { MovieId = 2, Caption = "Pulp Fiction", ReleaseYear = 1994, MovieLength = 140, InsertDate = DateTime.ParseExact("2021-12-22 11:43:11.777", "yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture), DeleteDate = null },
                new Movie { MovieId = 3, Caption = "Avatar", ReleaseYear = 2009, MovieLength = 170, InsertDate = DateTime.ParseExact("2021-12-22 16:14:25.437", "yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture), DeleteDate = DateTime.ParseExact("2021-12-22 16:17:50.937", "yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture) });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}